### ISSUE TITLE
Linting + goimports-on-save issues

### ISSUE THREAD

**Issue by justinfx** [DamnWidget/anaconda_go#9] opened 2017-03-06 05:54 UTC
I am seeing an issue with the fmt on save feature (default). When I save my changes to source code, the file will revert back to the previous change and remain dirty still. The json server log output suggests on a single save action that I first see a `goimports` action, followed by two client requests for `fast_lint`

It seems if I disable fmt on save, I only see a single `fast_lint` request on save and the problem doesn't occur. So both the linter and the fmt want to do modifications to the file at the same time and race each other.

**Comment by justinfx** [comment] 2017-03-06 05:57
A work around to this problem is to disable the fmt-on-save option, and create a custom save hook:
https://gist.github.com/justinfx/341cf167098254317a87de0fc00f45cb

Depends on this SublimeText3 package:
https://packagecontrol.io/packages/GoImports

I can put together a PR shortly for this as a Known Issues Workaround.

**Comment by DamnWidget** [comment] 2017-03-08 22:11
The workaround provided is merged and part of v0.1.8

**Comment by justinfx** [comment] 2017-05-08 01:17
I'm not sure if this is related to #12 , but this is still an annoying problem for me, even with linting disabled, and only using the "fmt on save" feature. When I save, I see the jsonserver receive and process the "goimports" request. Then the file gets updated but the tab remains dirty. The file does get written properly, but there must be a race condition where the buffer gets updated at the wrong time. 

Also, regarding the workaround I had contributed, it seems the "goimports" sublime package has a bug where if the file has syntax error when you run it, the file is left blank. So basically its not a great option as the workaround.

**Comment by DamnWidget** [comment] 2017-05-08 10:17
Hi Justin

I've been really busy last month or so (I am still), I will try to fix this one as soon as possible, the only solution for this one is to make it synchronous (right now it is an asynchronous call).

**Comment by justinfx** [comment] 2017-05-08 11:19
I know it's against your project goal to have synchronous calls. It may be ideal to expose the auto format command as an option the user can set, which would replace the async behaviour with the desired sync call. I can try and look into a merge request for the sync aspect if I have time. For now I have had to switch back to GoSublime because I simply couldn't get my file to save clean.

 I feel there are certain operations that should block. Formatting the file, for instance, is going to change the text. To me it doesn't make as much sense to do that in the background and let the user keep interacting with the file, only for it to finish formatting and change on them. Linting on the other hand is just a reporting mechanism that can continue to update. So it makes sense to be async.

**Comment by DamnWidget** [comment] 2017-05-08 13:13
The buffer gets lock in real only mode while the auto format operation is running even if it is asynchronous the problem is related with ST3 sending another save event that gets captured by the previous state of the buffer while the formatting is taking action. It is a classical race condition problem with not much chance to fix than make it synchronous, it's a shame yes but probably the only way.

**Comment by DamnWidget** [comment] 2017-05-10 14:45
I already fixed this, I will release it later today. As a side effect I removed your previous contribution as it's not needed anymore.

**Closed as completed** 2017-05-10 15:54 UTC

**Comment by justinfx** [comment] 2017-05-10 19:37
Fantastic! Looking forward to testing this. Thank you so much for working on it.

**Comment by justinfx** [comment] 2017-05-10 22:37
I'm trying this out now and finding that even though "anaconda_go_auto_format=true", the formatted no longer occurs on save hook. I can manually run the command via the command palette though. And then it still leaves the view dirty. I've tried completely removing and reinstalling the package, but no change. When I do code completions, I see the jsonserver log indicate that it is handling it. But I see no output related to handling goimport.

Should I be seeing the jsonserver log info about formatting?

**Comment by justinfx** [comment] 2017-05-10 22:50
Actually it makes sense that the view is left dirty after manually running the format command. So my question is just about whether you see any issues with the save hook not running anymore.

**Comment by DamnWidget** [comment] 2017-05-10 22:56
It's working fine for me, when I do Ctrl+S my buffer gets edited and then saved.

**Comment by justinfx** [comment] 2017-05-10 23:03
Sorry for the trouble. I found the problem. I still had an old save hook py file installed, related to this now removed workaround. Working as expected. Thanks again for the fix!

**Comment by justinfx** [comment] 2017-05-15 01:43
After using this new addition for a few days now, I wanted to give some feedback that could help the performance. I noticed within a very large GOPATH/project that goimports takes a bit of time to complete. This was also a problem in GoSublime, but that other plugin exposes the fmt command as an option to the user. So the way to get it to run faster is that I would use this as my format setting:

```json
"fmt_cmd": ["goimports", "-srcdir", "$_dir"]
```

`$_dir` is a GoSublime variable representing the dirname of the current file.

Would it be somewhat straight-forward to expose the "fmt" command to the settings? Does this approach have any value, being that formatting has been made a sync operation?

**Comment by DamnWidget** [comment] 2017-05-15 08:39
Hi @justinfx 
Expose options is a very trivial task.
